project_id = "zzgqcgtmmksvsurtiyqm"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
image_transformation_enabled = true

[auth]
enabled = true
port = 54328
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_captcha_enabled = false

[functions.auto-publish-news]
verify_jwt = false

[edge-runtime]
policy = "per_worker"
inspector_port = 8083