-- Add page content for Contact page to support multi-language
INSERT INTO contact_info (language_code, section_key, title, content, display_order, is_active) VALUES
-- Vietnamese content
('vi', 'page_title_vi', 'Tiêu đề trang', 'Liên hệ với chúng tôi', 1, true),
('vi', 'page_description_vi', 'Mô tả trang', 'Chúng tôi luôn sẵn sàng hỗ trợ và lắng nghe ý kiến của bạn', 2, true),
('vi', 'contact_info_title_vi', 'Tiêu đề thông tin liên hệ', 'Thông tin liên hệ', 3, true),
('vi', 'form_title_vi', 'Tiêu đề form', 'Gửi tin nhắn cho chúng tôi', 4, true),
('vi', 'form_name_label_vi', 'Nhãn tên', 'Họ và tên *', 5, true),
('vi', 'form_name_placeholder_vi', 'Placeholder tên', 'Nhập họ và tên', 6, true),
('vi', 'form_email_label_vi', 'Nhãn email', 'Email *', 7, true),
('vi', 'form_email_placeholder_vi', 'Placeholder email', 'Nhập email', 8, true),
('vi', 'form_phone_label_vi', 'Nhãn điện thoại', 'Số điện thoại', 9, true),
('vi', 'form_phone_placeholder_vi', 'Placeholder điện thoại', 'Nhập số điện thoại', 10, true),
('vi', 'form_subject_label_vi', 'Nhãn tiêu đề', 'Tiêu đề *', 11, true),
('vi', 'form_subject_placeholder_vi', 'Placeholder tiêu đề', 'Nhập tiêu đề', 12, true),
('vi', 'form_message_label_vi', 'Nhãn tin nhắn', 'Tin nhắn *', 13, true),
('vi', 'form_message_placeholder_vi', 'Placeholder tin nhắn', 'Nhập tin nhắn của bạn', 14, true),
('vi', 'form_submit_button_vi', 'Nút gửi', 'Gửi tin nhắn', 15, true),
('vi', 'form_submitting_button_vi', 'Nút đang gửi', 'Đang gửi...', 16, true),
('vi', 'success_title_vi', 'Tiêu đề thành công', 'Gửi thành công', 17, true),
('vi', 'success_message_vi', 'Tin nhắn thành công', 'Tin nhắn của bạn đã được gửi. Chúng tôi sẽ liên hệ lại sớm nhất có thể.', 18, true),
('vi', 'error_title_vi', 'Tiêu đề lỗi', 'Lỗi', 19, true),
('vi', 'error_message_vi', 'Tin nhắn lỗi', 'Có lỗi xảy ra khi gửi tin nhắn. Vui lòng thử lại.', 20, true),

-- English content  
('en', 'page_title_en', 'Page Title', 'Contact Us', 1, true),
('en', 'page_description_en', 'Page Description', 'We are always ready to support and listen to your feedback', 2, true),
('en', 'contact_info_title_en', 'Contact Info Title', 'Contact Information', 3, true),
('en', 'form_title_en', 'Form Title', 'Send us a message', 4, true),
('en', 'form_name_label_en', 'Name Label', 'Full Name *', 5, true),
('en', 'form_name_placeholder_en', 'Name Placeholder', 'Enter your full name', 6, true),
('en', 'form_email_label_en', 'Email Label', 'Email *', 7, true),
('en', 'form_email_placeholder_en', 'Email Placeholder', 'Enter your email', 8, true),
('en', 'form_phone_label_en', 'Phone Label', 'Phone Number', 9, true),
('en', 'form_phone_placeholder_en', 'Phone Placeholder', 'Enter your phone number', 10, true),
('en', 'form_subject_label_en', 'Subject Label', 'Subject *', 11, true),
('en', 'form_subject_placeholder_en', 'Subject Placeholder', 'Enter subject', 12, true),
('en', 'form_message_label_en', 'Message Label', 'Message *', 13, true),
('en', 'form_message_placeholder_en', 'Message Placeholder', 'Enter your message', 14, true),
('en', 'form_submit_button_en', 'Submit Button', 'Send Message', 15, true),
('en', 'form_submitting_button_en', 'Submitting Button', 'Sending...', 16, true),
('en', 'success_title_en', 'Success Title', 'Message Sent', 17, true),
('en', 'success_message_en', 'Success Message', 'Your message has been sent. We will contact you as soon as possible.', 18, true),
('en', 'error_title_en', 'Error Title', 'Error', 19, true),
('en', 'error_message_en', 'Error Message', 'An error occurred while sending the message. Please try again.', 20, true);