// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzgqcgtmmksvsurtiyqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6Z3FjZ3RtbWtzdnN1cnRpeXFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NjM1MjksImV4cCI6MjA3MDAzOTUyOX0.AV_9vIxDXw9-riQ0AQSRRI1aMU-b4vviMftunIls0rM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});